name: anatomica
description: Anatomica mobile application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+16

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_cache_manager: ^3.3.0
  flutter_rating_bar: ^4.0.1
  dio: ^4.0.6
  connectivity_plus: ^3.0.2
  get_it: ^7.2.0
  app_settings: ^4.2.0
  equatable: ^2.0.3
  shimmer: ^2.0.0
  flutter_svg: ^1.0.3
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  yandex_mapkit: ^3.1.1
  geolocator: ^9.0.1
  permission_handler: ^10.0.0
  pin_code_fields: ^7.4.0
  keyboard_dismisser: ^3.0.0
  share_plus: ^6.0.1
  url_launcher: ^6.1.7
  mask_text_input_formatter: ^2.4.0
  clipboard: ^0.1.3
  freezed_annotation: ^2.1.0
  youtube_player_flutter: ^8.0.0
  open_file_plus: ^3.4.0
  flutter_cupertino_datetime_picker:
    git:
      url: https://github.com/AbuAbdulloh/flutter_cupertino_datetime_picker.git
  animated_size_and_fade: ^3.0.0
  jiffy: ^5.0.0
  image_picker: ^0.8.5+3
  lottie: ^1.4.1
  formz: ^0.4.1
  json_annotation: ^4.6.0
  flutter_html: ^3.0.0-alpha.2
  rxdart: ^0.27.5
  easy_localization: ^3.0.1
  flutter_inappwebview: ^5.7.1
  map_launcher: ^2.4.0
  path_provider: ^2.0.2
  inview_notifier_list: ^3.0.0
  scroll_to_index: ^3.0.1
  carousel_slider: ^4.1.1
  scrollable_positioned_list: ^0.3.5
  webview_flutter: ^3.0.4
  photo_view: ^0.14.0
  smooth_page_indicator: ^1.0.1
  onesignal_flutter: ^3.5.1
dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  freezed: ^2.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/anatomica_logo.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/lotties/
    - assets/fonts/averta_cy/
    - assets/icons/
    - assets/images/
    - assets/books/
    - assets/icons/magazine/
    - assets/icons/auth/
    - assets/icons/vacancy/
    - assets/icons/map_screen/
    - assets/icons/global/
    - assets/icons/profile/
    - assets/icons/home/
    - lib/assets/translations/ru.json
    - lib/assets/translations/uz.json
    - lib/assets/translations/
  fonts:
    - family: Averta CY
      fonts:
        - asset: assets/fonts/averta_cy/AvertaCyrillicBlack.otf
          weight: 900
        - asset: assets/fonts/averta_cy/AvertaCyrillicExtraBold.otf
          weight: 800
        - asset: assets/fonts/averta_cy/AvertaCyrillicBold.otf
          weight: 700
        - asset: assets/fonts/averta_cy/AvertaCyrillicSemiBold.otf
          weight: 600
        - asset: assets/fonts/averta_cy/AvertaCyrillicRegular.otf
          weight: 400
        - asset: assets/fonts/averta_cy/AvertaCyrillicThin.otf
          weight: 300
        - asset: assets/fonts/averta_cy/AvertaCyrillicExtraThin.otf
          weight: 200
    - family: IBM Plex Serif
      fonts:
        - asset: assets/fonts/ibm_plex_serif/IBMPlexSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/ibm_plex_serif/IBMPlexSerif-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ibm_plex_serif/IBMPlexSerif-Medium.ttf
          weight: 500
        - asset: assets/fonts/ibm_plex_serif/IBMPlexSerif.ttf
          weight: 400
        - asset: assets/fonts/ibm_plex_serif/IBMPlexSerif-Light.ttf
          weight: 300
        - asset: assets/fonts/ibm_plex_serif/IBMPlexSerif-ExtraLight.ttf
          weight: 200
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue Book.ttf
    - family: MonoType
      fonts:
        - asset: assets/fonts/Monotype  - Gill Sans Nova Cn Medium.ttf
    - family: Monterchi
      fonts:
        - asset: assets/fonts/Monterchi Bold.otf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MONTSERRAT-BOLD.TTF
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MONTSERRAT-LIGHT.TTF
    - family: Mozer Book
      fonts:
        - asset: assets/fonts/Mozer-Book.ttf
