name: anatomica
description: Anatomica mobile application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  get_it: ^7.2.0
  equatable: ^2.0.3
  shimmer: ^2.0.0
  flutter_svg: ^1.1.1+1
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  yandex_mapkit: ^3.0.3
  geolocator: ^8.2.0
  permission_handler: ^10.0.0
  pin_code_fields: ^7.4.0
  keyboard_dismisser: ^3.0.0
  buttons_tabbar: ^1.3.6
  tab_indicator_styler: ^2.0.0
  flutter_sticky_header: ^0.6.4
  share_plus: ^4.0.10+1
  url_launcher: ^6.1.5
  mask_text_input_formatter: ^2.4.0
  clipboard: ^0.1.3
  flutter_spinkit: ^5.1.0
  freezed_annotation: ^2.1.0
  flutter_cupertino_datetime_picker:
    git:
      url: https://github.com/AbuAbdulloh/flutter_cupertino_datetime_picker.git
  animated_size_and_fade: ^3.0.0
  jiffy: ^5.0.0
  image_picker: ^0.8.5+3
  lottie: ^1.4.1
  formz: ^0.4.1
  json_annotation: ^4.6.0
  visibility_detector: ^0.2.2


dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  freezed: ^2.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/anatomica_logo.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/fonts/averta_cy/
    - assets/icons/
    - assets/images/
    - assets/icons/magazine/
    - assets/icons/auth/
    - assets/icons/vacancy/
    - assets/icons/map_screen/
    - assets/icons/global/
    - assets/icons/profile/
  fonts:
    - family: Averta CY
      fonts:
        - asset: assets/fonts/averta_cy/AvertaCyrillicBlack.otf
          weight: 900
        - asset: assets/fonts/averta_cy/AvertaCyrillicExtraBold.otf
          weight: 800
        - asset: assets/fonts/averta_cy/AvertaCyrillicBold.otf
          weight: 700
        - asset: assets/fonts/averta_cy/AvertaCyrillicSemiBold.otf
          weight: 600
        - asset: assets/fonts/averta_cy/AvertaCyrillicRegular.otf
          weight: 400
        - asset: assets/fonts/averta_cy/AvertaCyrillicThin.otf
          weight: 300
        - asset: assets/fonts/averta_cy/AvertaCyrillicExtraThin.otf
          weight: 200
