name: anatomica
description: Anatomica mobile application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  screen_brightness: ^0.2.1
  dio: ^4.0.6
  get_it: ^7.2.0
  equatable: ^2.0.3
  shimmer: ^2.0.0
  flutter_svg: ^1.0.3
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  yandex_mapkit: ^3.1.1
  geolocator: ^9.0.1
  permission_handler: ^10.0.0
  pin_code_fields: ^7.4.0
  keyboard_dismisser: ^3.0.0
  buttons_tabbar: ^1.3.6
  tab_indicator_styler: ^2.0.0
  flutter_sticky_header: ^0.6.4
  share_plus: ^6.0.1
  url_launcher: ^6.1.5
  mask_text_input_formatter: ^2.4.0
  clipboard: ^0.1.3
  flutter_spinkit: ^5.1.0
  freezed_annotation: ^2.1.0
  youtube_player_flutter: ^8.0.0
  encrypt: ^5.0.1
#  epub_view:
#    path: './custom_packages/epub_view'
  flutter_cupertino_datetime_picker:
    git:
      url: https://github.com/AbuAbdulloh/flutter_cupertino_datetime_picker.git
#  munir_epub_reader:
#    git:
#      url: https://gitlab.uicgroup.tech/munir/munir-epub-reader-flutter.git
#      ref: d0795dcc77db6f0f2fb05728132799580e112e92
  animated_size_and_fade: ^3.0.0
  jiffy: ^5.0.0
  image_picker: ^0.8.5+3
  lottie: ^1.4.1
  formz: ^0.4.1
  json_annotation: ^4.6.0
  flutter_html: ^3.0.0-alpha.2
  rxdart: ^0.27.5
  easy_localization: ^3.0.1
  flutter_inappwebview: ^5.7.1
  map_launcher: ^2.4.0
#  firebase_crashlytics: ^3.0.2
  path_provider: ^2.0.2
#  firebase_core: ^2.1.0
  flutter_markdown: ^0.6.12
  local_assets_server: ^2.0.2+12
  inview_notifier_list: ^3.0.0
  scroll_to_index: ^3.0.1
  carousel_slider: ^4.1.1
dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  freezed: ^2.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/anatomica_logo.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/fonts/averta_cy/
    - assets/icons/
    - assets/images/
    - assets/books/
    - assets/icons/magazine/
    - assets/icons/auth/
    - assets/icons/vacancy/
    - assets/icons/map_screen/
    - assets/icons/global/
    - assets/icons/profile/
    - lib/assets/translations/ru.json
    - lib/assets/translations/uz.json
    - lib/assets/translations/
  fonts:
    - family: Averta CY
      fonts:
        - asset: assets/fonts/averta_cy/AvertaCyrillicBlack.otf
          weight: 900
        - asset: assets/fonts/averta_cy/AvertaCyrillicExtraBold.otf
          weight: 800
        - asset: assets/fonts/averta_cy/AvertaCyrillicBold.otf
          weight: 700
        - asset: assets/fonts/averta_cy/AvertaCyrillicSemiBold.otf
          weight: 600
        - asset: assets/fonts/averta_cy/AvertaCyrillicRegular.otf
          weight: 400
        - asset: assets/fonts/averta_cy/AvertaCyrillicThin.otf
          weight: 300
        - asset: assets/fonts/averta_cy/AvertaCyrillicExtraThin.otf
          weight: 200
    - family: IBM Plex Serif
      fonts:
        - asset: assets/fonts/ibm_plex_serif/IBMPlexSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/ibm_plex_serif/IBMPlexSerif-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ibm_plex_serif/IBMPlexSerif-Medium.ttf
          weight: 500
        - asset: assets/fonts/ibm_plex_serif/IBMPlexSerif.ttf
          weight: 400
        - asset: assets/fonts/ibm_plex_serif/IBMPlexSerif-Light.ttf
          weight: 300
        - asset: assets/fonts/ibm_plex_serif/IBMPlexSerif-ExtraLight.ttf
          weight: 200
